### ISSUE TITLE
Crashing daemon

### ISSUE THREAD

**Issue by pinpins** [KomodoPlatform/komodo#200]
Ubuntu 16.04

Occasionally, daemon crashes leaving following in debug.log
Referring to master tree

2019-07-19 23:30:01 ERROR: AcceptToMemoryPool: tx inputs not found
2019-07-19 23:30:37 ERROR: ContextualCheckBlock: contains a non-final transaction
2019-07-20 19:49:19

**Comment by tonymorony** [comment]
Could you provide more information please:
 
- from what repo/branch/commit daemon are you using, if it's pre-compiled binary - what version?
- is it KMD chain or another one?
- is it crashing on some specific height / after specific actions?

**Comment by pinpins** [comment]
1. master from https://github.com/KomodoPlatform/komodo
2. it is just KMD chain
3. no specific action was identified.

**Comment by pinpins** [comment]
catched more detailed error in unix shell, making daemon to crash

000000000000000000000000000000000 0
komodod: /home/pool/komodo/depends/x86_64-unknown-linux-gnu/share/../include/boost/thread/pthread/recursive_mutex.hpp:118: void boost::recursive_mutex::unlock(): Assertion `!pthread_mutex_unlock(&m)' failed.

**Comment by pinpins** [comment]
Crashed again
2019-08-03 13:04:02 ERROR: AcceptToMemoryPool: tx inputs not found
2019-08-03 13:04:02 ERROR: AcceptToMemoryPool: tx inputs not found
2019-08-03 13:05:08 ERROR: ContextualCheckBlock: contains a non-final transaction

**Comment by pinpins** [comment]
Anyone?

**Comment by ca333** [comment]
please pull and rebuild @pinpins
