### ISSUE TITLE
THROW_IF_SYNCING incorrectly disabled for what reason?

### ISSUE THREAD

**Issue by leto** [KomodoPlatform/komodo#360]
`THROW_IF_SYNCING` is an important mitigation against metadata leakage and it was recently disabled in 2 places and forgot to be disabled in the 3rd place.

Why was this done without asking for feedback on the privacy/security implications?

**Comment by ca333** [comment]
Thank you for the information @leto - i created https://github.com/KomodoPlatform/komodo/tree/privacy for privacy feature utilising SmartChains with https://github.com/KomodoPlatform/komodo/commit/1559b80bd54ebcf2d017ae285d444af2e1814781. 

This [change](https://github.com/DeckerSU/KomodoOcean/commit/885d759bb23f8606d2c914c10e548f56c9a2cb7c) was added cuz detecting the sync state wasn't/isn't reliable (on our todo) - and when pushing it to our dev branch i kept `z_mergetoaddress` 'safe' as we were using the same dev repo/branch for few merge-OPs - 'sorted' this with https://github.com/KomodoPlatform/komodo/commit/4db55911612c772f6a124c1898a8d35452cf1346

**Comment by leto** [comment]
@ca333 I will assume you and Pirate understand the privacy implications of this and only concern myself with Hush
