### ISSUE TITLE
When starting komodod with -datadir arg on Windows, it still try to fetch .conf from default datadir.

### ISSUE THREAD

**Issue by StrobFX** [KomodoPlatform/komodo#465]
When starting komodod with custom data directory (set with -datadir= arg) on Windows, it still try to fetch komodo.conf from default datadir (AppData\Roaming\Komodo)
Which result in error: 
error: incorrect rpcuser or rpcpassword (authorization failed)

tested with latest dev version 117dfd5 on windows 10.

**Comment by tonymorony** [comment]
> When starting komodod with custom data directory (set with -datadir= arg) on Windows, it still try to fetch komodo.conf from default datadir (AppData\Roaming\Komodo)
> Which result in error:
> error: incorrect rpcuser or rpcpassword (authorization failed)
> 
> tested with latest dev version [117dfd5](https://github.com/KomodoPlatform/komodo/commit/117dfd50e15011928c94cba90f2c85129a0ea324) on windows 10.

@StrobFX -datadir param using for blockchain data dir specifying for custom config path please use -conf param

e.g. https://manpages.ubuntu.com/manpages/precise/en/man5/bitcoin.conf.5.html

```
 The configuration file is not automatically created; you can create it using your favorite
       plain-text  editor.  By default, bitcoind(1) will look for a file named bitcoin.conf(5) in
       the bitcoin data directory, but both the data directory and the  configuration  file  path
       may be changed using the '-datadir' and '-conf' command-line arguments.
```

**Comment by StrobFX** [comment]
Yes it was created but I still got the error cause komodod was looking for it to be in C:\Users\username\AppData\Roaming\Komodo instead of the specified custom datadir. When copying the .conf from the custom datadir to the default one, the error stopped.
