### ISSUE TITLE
rm `test_block_ser`

### ISSUE THREAD

**Issue by ca333** [KomodoPlatform/komodo#547]
As all changes have been verified on the accepting to the `dev` branch stage, or within `hfnet` testing, and passing through `dev->beta->master` haven't new changes -> LGTM.

**p.s.** `test_block_ser` in `TestHarakaRemoval` tests could be safely deleted.

_Originally posted by @DeckerSU in https://github.com/KomodoPlatform/komodo/pull/544#pullrequestreview-1003592043_

**Comment by dimxy** [comment]
I actually fixed this test in PR #559
