### ISSUE TITLE
Please port z_gettreestate RPC.

### ISSUE THREAD

**Issue by artemii235** [KomodoPlatform/komodo#558]
https://zcash-rpc.github.io/z_gettreestate.html

It is required for `lightwalletd` GetTreeState method (https://github.com/zcash/lightwalletd/blob/2d3943b8e995a3b2c5648ec9859dccc67c535386/walletrpc/service.proto#L177). With this, we can initialize PIRATE light wallet database with some recent block data in AtomicDEX, at least for newly created addresses. It will help to decrease first PIRATE activation time significantly. As of now, it may take 30 minutes (or even more) to scan all blocks data, searching for specific address transactions.

cc @ca333

**Comment by DeckerSU** [comment]
Sorry for stealing work from @dimxy , but seems i already have a solution for this:
[z_gettreestate_patch.zip](https://github.com/KomodoPlatform/komodo/files/9252790/z_gettreestate_patch.zip)
Patch should be applied to the actual `dev` branch, like:
```
git apply -v z_gettreestate_patch.diff
```

**Comment by ca333** [comment]
> Sorry for stealing work from @dimxy , but seems i already have a solution for this: [z_gettreestate_patch.zip](https://github.com/KomodoPlatform/komodo/files/9252790/z_gettreestate_patch.zip) Patch should be applied to the actual `dev` branch, like:
> 
> ```
> git apply -v z_gettreestate_patch.diff
> ```
> 
> Example:
> 
> ```
> komodo-cli z_gettreestate 2963000
> {
>   "hash": "05df1e97a54834fe5732eaef7d5f5423c01214b543c903ba5580d303bf640da5",
>   "height": 2963000,
>   "time": 1656221217,
>   "sprout": {
>     "commitments": {
>       "finalRoot": "4e43e43d3569c1155cc9340f46b58425e3d86890076739f19298bc66e6a7acf2",
>       "finalState": "01cea87e1dc646a5a18c87c193d036bf5a748278b6616a0ea8be8e77f95fda413301348e893f7de629a729894c7d91c23eeb9ffe29ceed39663fe0e9115add3b722f0f000000014787762c4a0ac2c6453d92b74c16d720bd02ebefbee9a1480e5eface50bdf03901ae91a4efd791efe24d0c6b0178b3e54f1af8d776db380b267d0b49af8f12881c01c0377146e2d65ad0eb9a2b7364daf696ee25e8fb4c26364bd26b7c61229754df01f7c8b8be6e04efcb12930490bccbf1e06de6f26a975b63e829996325c521666601ff89bca80abc097b06e1786cf8263748857a671317b0cb0be74d87fc78733c39000127413e8f2567638e67c78b331a525aaf543259526aff5c6f02b880588cb591a5000127a22803ee858393c89fe91efb38be2d877efded52f2759aa50aef4d30ba427c01521229edfa9fe3e02d180a51a80757927babbca4faa18fdead0473fa4db3621e010d8712ef663a7dae2cfe880793d158cebef760631fb1cb73b232bdc7b4bba7bf01d1c650f25a9bf3df2c9eea1974a86f6bfe18ceb8311ecea2da7e307e964c5b28"
>     }
>   },
>   "sapling": {
>     "commitments": {
>       "finalRoot": "1ccce5445c492209c1d6e3e0bf21711e6f4012fddb724073dca473eb34a7d8a2",
>       "finalState": "01420a724bddb86cabc1b7e6bae9728e785459e0ef01d4abf3d1fe645ca7c1954201308874686c237c8c3865317062ac079f789032c9b8a14a72cec1b83c9af1843f0800016d3ab69f0342c3895345d3d33871b2997c02a86734b347fa0561b4fdaca2886001a2d8e9ea91e99386db91e0f741c16777a73d170aa99fb46d93b1eaa230d5663b016b5e82c76069e53d8d0830230e3edd00258909bc6b43f8cd7673708ab8488b0f012643ee92e0aac4eaec6cdd587e26ce545285a84a19e8346bd8f3382a76d0ec47015d623e14a2b99e2ef0a47c4a17820e199de783ac1b38f0c23304ccfa4c61bc650001c9b1d7e2dbef249d11ebf3fc5c12077c881b30c6cb69cfae0412346fc38e3d5e"
>     }
>   }
> ```

thanks! please PR it into `dev`

**Comment by DeckerSU** [comment]
The issue has been resolved and is now closed.
